name: CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  linux:
    runs-on: ubuntu-latest
    container: veriblock/btcdev
    strategy:
      matrix:
        host: ["x86_64-pc-linux-gnu"]
    env:
      CC: gcc
      CXX: g++
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
#    - if: matrix.host == 'x86_64-w64-mingw32'
#      name: mingw preinstall script
#      run: update-alternatives --config x86_64-w64-mingw32-g++
    - name: install dependencies
      run: |
        cd depends
        make HOST=${{ matrix.host }} NO_QT=1
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: CONFIG_SITE=$PWD/depends/${{ matrix.host }}/share/config.site ./configure
        --without-gui
        --enable-werror
        --disable-bench
        #--enable-lcov
        #--enable-lcov-branch-coverage


    - name: make
      run: make -j2
    - name: make check
      timeout-minutes: 20
      run: make check
#    - name: Collect coverage
#      run: |
#        lcov -c -d src -o cov.info
#        gcovr --xml cov.xml -j2 -v -s -b -r src
#    - name: Run sonarqube
#      run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}
