name: CI

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  sanitizer:
    strategy:
      fail-fast: true
      matrix:
        sanitizer: [thread, address]
    runs-on: [self-hosted, linux]
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure
          --without-gui
          --enable-werror
          --with-sanitizers=${{ matrix.sanitizer }}
      - name: make
        run: make -j2
      - name: make check
        timeout-minutes: 10
        run: make check

  coverage:
    runs-on: [self-hosted, linux]
    env:
      CC: gcc
      CXX: g++
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
        --without-gui
        --enable-werror
        --enable-lcov
        --enable-lcov-branch-coverage
        --disable-bench

    - name: make
      run: make -j2
    - name: make check
      timeout-minutes: 10
      run: make check
    - name: Collect coverage
      run: |
        lcov -c -d src -o cov.info
        gcovr --xml cov.xml -j2 -v -s -b -r src
    - name: Run sonarqube
      run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}