name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ["x86_64-pc-linux-gnu", "x86_64-w64-mingw32"]
    env:
      NO_QT: 1
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - if: matrix.host == 'x86_64-w64-mingw32'
        name: mingw preinstall script
        run: |
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ g++ 90
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc gcc 90
      - name: install dependencies
        run: |
          cd depends
          make HOST=${{ matrix.host }} -j
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: CONFIG_SITE=$PWD/depends/${{ matrix.host }}/share/config.site ./configure
          --without-gui
          --enable-werror
          --disable-bench
          --disable-gmock
      - name: make
        run: make -j2
      - name: make check
        timeout-minutes: 20
        run: make check
