name: Update veriblock-pop-cpp

on:
  repository_dispatch:
    types: update

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: veriblock-pop-cpp
        run: |
          echo ${{ github.event.client_payload.sha }}